// Canada Post integration (server-only).
//
// Two surfaces:
//   1. `getRates()` — quotes shipping cost for a cart → checkout picks one.
//   2. `createShipment()` — buys a real label + returns the tracking PIN and
//      a link to the PDF. Admin "Buy label" flow calls this.
//
// Canada Post's API is XML-in / XML-out over HTTPS with HTTP Basic auth.
// We keep the XML parsing narrow (regex-based tag extraction) because the
// response schemas we consume are small and stable. If we ever need to read
// deeply-nested attributes, swap in `fast-xml-parser`.
//
// Sandbox vs production:
//   CANADA_POST_MODE=development → ct.soa-gw.canadapost.ca (free test labels)
//   CANADA_POST_MODE=production  → soa-gw.canadapost.ca    (real charges)
//
// Auth: HTTP Basic (username:password) where username / password are the
// "API user" credentials you create in Canada Post's Developer Program.

import { normalizeCountry } from './countries'

const HOST_DEV = 'https://ct.soa-gw.canadapost.ca'
const HOST_PROD = 'https://soa-gw.canadapost.ca'

const CUSTOMER_NUMBER = process.env.CANADA_POST_CUSTOMER_NUMBER || ''
const API_USER = process.env.CANADA_POST_API_USERNAME || ''
const API_PASS = process.env.CANADA_POST_API_PASSWORD || ''
const MODE = (process.env.CANADA_POST_MODE || 'development').toLowerCase()
const ORIGIN_POSTAL = (process.env.CANADA_POST_ORIGIN_POSTAL || '').replace(/\s+/g, '').toUpperCase()

const ORIGIN_NAME = process.env.CANADA_POST_ORIGIN_NAME || ''
const ORIGIN_ADDRESS_LINE = process.env.CANADA_POST_ORIGIN_ADDRESS_LINE || ''
const ORIGIN_CITY = process.env.CANADA_POST_ORIGIN_CITY || ''
const ORIGIN_PROVINCE = (process.env.CANADA_POST_ORIGIN_PROVINCE || '').toUpperCase()
const ORIGIN_PHONE = process.env.CANADA_POST_ORIGIN_PHONE || ''

function host(): string {
  return MODE === 'production' ? HOST_PROD : HOST_DEV
}

function authHeader(): string {
  return 'Basic ' + Buffer.from(`${API_USER}:${API_PASS}`).toString('base64')
}

/** Enough config to quote rates (subset of what label creation needs). */
export function canPostRateQuotes(): boolean {
  return Boolean(CUSTOMER_NUMBER && API_USER && API_PASS && ORIGIN_POSTAL)
}

/** Enough config to actually buy a label (rate quotes + full origin address). */
export function canPostCreateShipment(): boolean {
  return (
    canPostRateQuotes() &&
    Boolean(ORIGIN_NAME && ORIGIN_ADDRESS_LINE && ORIGIN_CITY && ORIGIN_PROVINCE && ORIGIN_PHONE)
  )
}

// ── XML helpers (kept intentionally minimal) ─────────────────────────────────

/** Escape values inside XML text nodes / attributes. */
function xmlEscape(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/** Pull the first `<tag>...</tag>` value out of an XML string. Returns null
 *  if the tag isn't present. Handles namespaces via a permissive regex. */
function extractTag(xml: string, tag: string): string | null {
  const re = new RegExp(`<(?:[a-z0-9]+:)?${tag}[^>]*>([\\s\\S]*?)</(?:[a-z0-9]+:)?${tag}>`, 'i')
  const m = xml.match(re)
  return m ? m[1].trim() : null
}

/** Pull every `<tag>...</tag>` block (for repeating price-quotes etc). */
function extractTagAll(xml: string, tag: string): string[] {
  const re = new RegExp(`<(?:[a-z0-9]+:)?${tag}[^>]*>([\\s\\S]*?)</(?:[a-z0-9]+:)?${tag}>`, 'gi')
  const out: string[] = []
  let m: RegExpExecArray | null
  while ((m = re.exec(xml)) !== null) out.push(m[1])
  return out
}

/** Extract an attribute like `<link rel="label" href="..."/>` — attribute
 *  read is naive but the source XML is generated by Canada Post's stable
 *  schema, so overfitting is fine. */
function extractLinkHref(xml: string, rel: string): string | null {
  const re = new RegExp(`<link[^>]*rel="${rel}"[^>]*href="([^"]+)"`, 'i')
  const m = xml.match(re)
  return m ? m[1] : null
}

// ── Public types ─────────────────────────────────────────────────────────────

export type CanadaPostRateQuote = {
  serviceCode: string     // e.g. "DOM.RP" (Regular Parcel) or "DOM.XP" (Xpresspost)
  serviceName: string     // human-readable
  totalCents: number      // grand total including taxes/fuel
  transitDays: number | null
}

export type CanadaPostShipmentResult = {
  shipmentId: string
  trackingPin: string
  labelUrl: string        // href to a PDF — call getLabelPdf(url) to download
  totalCents: number
}

export type ShippingAddress = {
  name: string
  line1: string
  line2?: string
  city: string
  region: string          // province code (e.g. "ON")
  postal: string
  country: string         // ISO-2 (e.g. "CA", "US")
  phone?: string
}

// ── getRates ─────────────────────────────────────────────────────────────────

/** Get shipping-rate quotes from origin postal → destination postal for a
 *  parcel of the given weight. Returns an empty array on any failure — this
 *  is a "nice to show" API surface, not a critical path (checkout falls back
 *  to flat shipping when the API fails). */
export async function getRates(input: {
  toPostal: string
  toCountry: string
  weightGrams: number
  lengthCm: number
  widthCm: number
  heightCm: number
}): Promise<CanadaPostRateQuote[]> {
  if (!canPostRateQuotes()) return []
  const toPostal = input.toPostal.replace(/\s+/g, '').toUpperCase()
  const weightKg = Math.max(0.1, input.weightGrams / 1000)

  // Canada Post's "get rates" endpoint accepts either a domestic or a US /
  // international destination — the destination sub-tree is what varies.
  let destinationXml: string
  const toCountry = normalizeCountry(input.toCountry)
  if (toCountry === 'CA') {
    destinationXml = `<domestic><postal-code>${xmlEscape(toPostal)}</postal-code></domestic>`
  } else if (toCountry === 'US') {
    destinationXml = `<united-states><zip-code>${xmlEscape(toPostal)}</zip-code></united-states>`
  } else {
    destinationXml = `<international><country-code>${xmlEscape(toCountry)}</country-code></international>`
  }

  const body =
    `<?xml version="1.0" encoding="UTF-8"?>` +
    `<mailing-scenario xmlns="http://www.canadapost.ca/ws/ship/rate-v4">` +
    `<customer-number>${xmlEscape(CUSTOMER_NUMBER)}</customer-number>` +
    `<parcel-characteristics>` +
    `<weight>${weightKg.toFixed(2)}</weight>` +
    `<dimensions>` +
    `<length>${input.lengthCm.toFixed(1)}</length>` +
    `<width>${input.widthCm.toFixed(1)}</width>` +
    `<height>${input.heightCm.toFixed(1)}</height>` +
    `</dimensions>` +
    `</parcel-characteristics>` +
    `<origin-postal-code>${xmlEscape(ORIGIN_POSTAL)}</origin-postal-code>` +
    `<destination>${destinationXml}</destination>` +
    `</mailing-scenario>`

  let res: Response
  try {
    res = await fetch(`${host()}/rs/ship/price`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/vnd.cpc.ship.rate-v4+xml',
        'Accept': 'application/vnd.cpc.ship.rate-v4+xml',
        'Accept-language': 'en-CA',
        'Authorization': authHeader(),
      },
      body,
      cache: 'no-store',
    })
  } catch (e) {
    console.error('[canada-post/getRates] network:', (e as Error).message)
    return []
  }
  const text = await res.text()
  if (!res.ok) {
    console.error('[canada-post/getRates] http', res.status, text.slice(0, 500))
    return []
  }

  return extractTagAll(text, 'price-quote').flatMap((block) => {
    const serviceCode = extractTag(block, 'service-code') || ''
    const serviceName = extractTag(block, 'service-name') || serviceCode
    const dueRaw = extractTag(block, 'due')
    const totalCents = Math.round(parseFloat(dueRaw || '0') * 100)
    const days = extractTag(block, 'expected-transit-time')
    const transitDays = days ? parseInt(days, 10) : null
    if (!serviceCode || !Number.isFinite(totalCents) || totalCents <= 0) return []
    return [{ serviceCode, serviceName, totalCents, transitDays }]
  })
}

// ── createShipment ───────────────────────────────────────────────────────────

/** Create a non-contract shipment (pay-as-you-go, uses the credit card on
 *  your Canada Post account). Returns the tracking PIN and a link to the
 *  label PDF. Throws on any failure — caller should catch + surface to admin.
 *
 *  `serviceCode` — pick from `getRates()` results (e.g. "DOM.RP"). */
export async function createShipment(input: {
  serviceCode: string
  weightGrams: number
  lengthCm: number
  widthCm: number
  heightCm: number
  to: ShippingAddress
  /** Order number — shows up on the shipping label as customer reference. */
  orderNumber: string
}): Promise<CanadaPostShipmentResult> {
  if (!canPostCreateShipment()) {
    throw new Error('Canada Post is not fully configured for label creation')
  }
  const weightKg = Math.max(0.1, input.weightGrams / 1000)
  const toPostal = input.to.postal.replace(/\s+/g, '').toUpperCase()
  // Accept "Canada" / "United States" free-text and normalize to ISO-2 so
  // this function doesn't blow up on legacy order rows.
  const country = normalizeCountry(input.to.country)
  const isDomestic = country === 'CA'

  // Delivery spec varies slightly by destination country. We ship as a small
  // parcel with no signature and no card-on-delivery — merchant tunes later.
  const deliveryBlock = isDomestic
    ? `<domestic>` +
      `<name>${xmlEscape(input.to.name)}</name>` +
      `<company></company>` +
      `<address-details>` +
      `<address-line-1>${xmlEscape(input.to.line1)}</address-line-1>` +
      (input.to.line2 ? `<address-line-2>${xmlEscape(input.to.line2)}</address-line-2>` : '') +
      `<city>${xmlEscape(input.to.city)}</city>` +
      `<prov-state>${xmlEscape(input.to.region)}</prov-state>` +
      `<postal-zip-code>${xmlEscape(toPostal)}</postal-zip-code>` +
      `</address-details>` +
      `</domestic>`
    : `<united-states>` +
      `<name>${xmlEscape(input.to.name)}</name>` +
      `<company></company>` +
      `<address-details>` +
      `<address-line-1>${xmlEscape(input.to.line1)}</address-line-1>` +
      (input.to.line2 ? `<address-line-2>${xmlEscape(input.to.line2)}</address-line-2>` : '') +
      `<city>${xmlEscape(input.to.city)}</city>` +
      `<state>${xmlEscape(input.to.region)}</state>` +
      `<zip-code>${xmlEscape(toPostal)}</zip-code>` +
      `</address-details>` +
      `</united-states>`

  const body =
    `<?xml version="1.0" encoding="UTF-8"?>` +
    `<non-contract-shipment xmlns="http://www.canadapost.ca/ws/ncshipment-v4">` +
    `<requested-shipping-point>${xmlEscape(ORIGIN_POSTAL)}</requested-shipping-point>` +
    `<delivery-spec>` +
    `<service-code>${xmlEscape(input.serviceCode)}</service-code>` +
    `<sender>` +
    `<name>${xmlEscape(ORIGIN_NAME)}</name>` +
    `<company></company>` +
    `<contact-phone>${xmlEscape(ORIGIN_PHONE)}</contact-phone>` +
    `<address-details>` +
    `<address-line-1>${xmlEscape(ORIGIN_ADDRESS_LINE)}</address-line-1>` +
    `<city>${xmlEscape(ORIGIN_CITY)}</city>` +
    `<prov-state>${xmlEscape(ORIGIN_PROVINCE)}</prov-state>` +
    `<postal-zip-code>${xmlEscape(ORIGIN_POSTAL)}</postal-zip-code>` +
    `</address-details>` +
    `</sender>` +
    `<destination>${deliveryBlock}</destination>` +
    `<parcel-characteristics>` +
    `<weight>${weightKg.toFixed(2)}</weight>` +
    `<dimensions>` +
    `<length>${input.lengthCm.toFixed(1)}</length>` +
    `<width>${input.widthCm.toFixed(1)}</width>` +
    `<height>${input.heightCm.toFixed(1)}</height>` +
    `</dimensions>` +
    `</parcel-characteristics>` +
    `<preferences><show-packing-instructions>false</show-packing-instructions></preferences>` +
    `<references><customer-ref-1>${xmlEscape(input.orderNumber)}</customer-ref-1></references>` +
    `</delivery-spec>` +
    `</non-contract-shipment>`

  const res = await fetch(
    `${host()}/rs/${encodeURIComponent(CUSTOMER_NUMBER)}/ncshipment`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/vnd.cpc.ncshipment-v4+xml',
        'Accept': 'application/vnd.cpc.ncshipment-v4+xml',
        'Accept-language': 'en-CA',
        'Authorization': authHeader(),
      },
      body,
      cache: 'no-store',
    },
  )
  const text = await res.text()
  if (!res.ok) {
    const errMsg = extractTag(text, 'description') || `HTTP ${res.status}`
    throw new Error(`Canada Post: ${errMsg}`)
  }

  const shipmentId = extractTag(text, 'shipment-id')
  const trackingPin = extractTag(text, 'tracking-pin')
  const labelUrl = extractLinkHref(text, 'label')
  if (!shipmentId || !trackingPin || !labelUrl) {
    throw new Error('Canada Post: shipment created but response is missing required fields')
  }

  // Total is returned in a separate nested block; parse it for the admin UI.
  const priceRaw = extractTag(text, 'due-amount') || extractTag(text, 'total-amount')
  const totalCents = priceRaw ? Math.round(parseFloat(priceRaw) * 100) : 0

  return { shipmentId, trackingPin, labelUrl, totalCents }
}

// ── getLabelPdf ──────────────────────────────────────────────────────────────

/** Fetch a label PDF from a Canada Post artifact URL. Returns the raw bytes
 *  as a Buffer — caller streams it to the admin (Content-Type: application/pdf). */
export async function getLabelPdf(labelUrl: string): Promise<Buffer> {
  const res = await fetch(labelUrl, {
    method: 'GET',
    headers: {
      'Accept': 'application/pdf',
      'Authorization': authHeader(),
    },
    cache: 'no-store',
  })
  if (!res.ok) throw new Error(`Canada Post label fetch: HTTP ${res.status}`)
  const buf = await res.arrayBuffer()
  return Buffer.from(buf)
}
